### ISSUE TITLE
Gradients in 'background' flipped incorrectly

### ISSUE THREAD

**Issue by jelisejev** [wikimedia/mediawiki-libs-node-cssjanus#33]
Hi,

First of all let me thank you for doing a great work. You project made implementing an RTL version of our project much easier. But I did encounter a small issue when flipping gradients: for some reason if the start position is set to "0%" it is changed to "100%". Just "0" remains unchanged as expected.

Here's an example https://cssjanus.github.io/#input/div%20%7B%0A%20%20background%3A%20linear-gradient(to%20left%2C%20%2300ff00%200%25%2C%20%23ff0000%20100%25)%3B%0A%20%20background%3A%20linear-gradient(to%20left%2C%20%2300ff00%200%2C%20%23ff0000%20100%25)%3B%0A%7D

**Comment by Krinkle** [comment]
Through trial-and-error I've narrowed this down to the `background` property. When using `background-image` the bug does not occur. Presumably one of the pattern matchers for background-position is triggered here.

**Comment by YairRand** [comment]
(Just pointing out that this is one of the bugs that are fixed in #36 .)

**Comment by Krinkle** [comment]
Exported to <https://phabricator.wikimedia.org/T333273>.
