### ISSUE TITLE
Flip properties in CSS transitions

### ISSUE THREAD

**Issue by neoncitylights** [wikimedia/mediawiki-libs-node-cssjanus#39]
In CSS transitions, they use other properties for manipulation in order to create a nice, smooth effect. It means in the value, they will have properties like `right`, and `left`. They should be flipped too :+1:

**Comment by codynguyen1116** [comment]
Err question, what happened to the developers? The latests changes were last year in November which is about say 3 months ago I think (if I can count. :P)

**Comment by georgebarnick** [comment]
Devs are still around especially @Krinkle. He's always around. I presume there's not a lot of activity because frequent changes aren't all that necessary.

**Comment by Krinkle** [comment]
@georgebarnick is correct. Wikimedia Foundation actively uses this project inside MediaWiki, which powers [Wikipedia](https://www.wikipedia.org/).

I'll check this out later early next week.

**Comment by codynguyen1116** [comment]
Any progress on this task yet?

**Comment by Krinkle** [comment]
@codynguyen1116 Could you supply a simple test case? I think I know what you're after but would like to make sure.

**Comment by codynguyen1116** [comment]
Err I'm not quite sure how to exactly explain it, but if you go to en.brickimedia.org on the default skin with the uselang query of "ar" (Arabic), the sidebar won't transition from the right on a tablet or phone. However, when viewing it on LTR it'll transition from the left.

**Comment by Krinkle** [comment]
Closing as https://github.com/Brickimedia/brickimedia/issues/455 and https://phabricator.wikimedia.org/T151142 are also closed, and there is no test case. If this is still an issue, please file a bug report at <https://phabricator.wikimedia.org/tag/cssjanus/> in the future.
