### ISSUE TITLE
Avoid flipping "ltr" or "left" in a data URI

### ISSUE THREAD

**Issue by trevorparscal** [wikimedia/mediawiki-libs-node-cssjanus#60]
Any URL that looks like a data URI should be skipped over. Otherwise image data will occasionally be corrupted, and in the case of the PHP port I've already seen the regular expressions engine simply blank out the entire stylesheet trying to operate on a data URI which was especially large.

[Test case](https://cssjanus.github.io/#input/x%20%7B%0Abackground-image%3A%20url(%22data%3Aimage%2Fsvg%2Bxml%2C%253C%20left%20right%22)%3B%0A%7D)

**Comment by Krinkle** [comment]
Exported to <https://phabricator.wikimedia.org/T333275>.
