### ISSUE TITLE
Support flipping mutiple values under a text-shadow or border-shadow rule

### ISSUE THREAD

**Issue by MatmaRex** [wikimedia/mediawiki-libs-node-cssjanus#62]
CSSJanus only supports flipping one text-shadow or border-shadow, while the CSS syntax allows multiple.

(Originally filed at https://phabricator.wikimedia.org/T62805)

Input:
```
* {
 text-shadow: red 99px -1px 1px, blue 99px 2px 1px;
}
```
Expected output:
```
* {
 text-shadow: red -99px -1px 1px, blue -99px 2px 1px;
}
```

Actual output:
```
* {
 text-shadow: red -99px -1px 1px, blue 99px 2px 1px;
}
```

**Comment by Krinkle** [comment]
Exported to <https://phabricator.wikimedia.org/T62805>.
