### ISSUE TITLE
Does not flip shorthand properties with expressions in them

### ISSUE THREAD

**Issue by tgr** [wikimedia/mediawiki-libs-node-cssjanus#82]
```
padding-left: calc( 1px +1em );
padding: 1px 2px 3px 4px;
padding: 1px 2px 3px calc( 1px + 1em );
```
([test](https://cssjanus.github.io/#input/padding-left%3A%20calc(%201px%20%2B1em%20)%3B%0Apadding%3A%201px%202px%203px%204px%3B%0Apadding%3A%201px%202px%203px%20calc(%201px%20%2B%201em%20)%3B%0A))
The first two lines are flipped, the last is not.

**Comment by YairRand** [comment]
(Pointing out that this is another bug which was fixed in #36 .)

**Comment by moabualruz** [comment]
I submitted a PR for it https://github.com/cssjanus/cssjanus/pull/89, it should fix it

**Comment by Krinkle** [comment]
Exported to <https://phabricator.wikimedia.org/T333276>.
