### ISSUE TITLE
Inconsistent flipping behavior breaks custom CSS properties

### ISSUE THREAD

**Issue by HumansCanWinElves** [wikimedia/mediawiki-libs-node-cssjanus#88]
When the word "right" or "left" is used as part of the name of a custom CSS property, the name is flipped by CSSJanus when the property is assigned, but not when the property is used, those breaking it's functionality.

Example input:
<pre>
body.theme-dark {
    --right-rail-bg: blue;
}

.right-rail {
    background: var(--right-rail-bg);
}
</pre>

CSSJanus output:
<pre>
body.theme-dark {
    --left-rail-bg: blue;
}

.right-rail {
    background: var(--right-rail-bg); /* invalid */
}
</pre>

It is probably better to not change custom property names at all, but it should at least be consistent.

**Comment by Krinkle** [comment]
Exported to <https://phabricator.wikimedia.org/T333277>.
